### ISSUE TITLE
Variations: Transparency and Glow

### ISSUE THREAD

**Issue by nnystyxx** [ChiselsAndBits/FlatColoredBlocks#1]
This will be a question, more than anything: is it possible, within the scope of FCB's code, to create transparent blocks and blocks that self-illuminate? Colored glass would certainly do the stained glass window crowd a favor, and self-illumination would be very stunning for low-light displays and 'magic' things. I was inspired partly by Armourer's Workshop, RiskyKen's 1.7.10 mod which featured HSV-colorable normal, transparent, glowing, and glowing transparent blocks, all of which offered a lot of variety.

The reason I ask why it's possible: I understand that FCB generates -tons- of colors and shades at any given time, and the Crafting Tool is already a saving grace in terms of limiting what's visible to narrow a search. How would one diversify that? A 'transparent' and a 'glowing' tool? A toggle or sliders of some sort on the UI?

I'm very interested in this, not just from a 'gimme feature' standpoint, but also one of feasibility. Generating it all is one thing, but implementing it in a smooth way that doesn't cause the game to explode is definitely another. If it -were- possible, and without a backbreaking amount of work, I think it would make quite a splash.

**Comment by AlgorithmX2** [comment]
I am quite fond of the idea to add semi-transparent shades, I believe that the stained glass possibilities would be pretty impressive, especially if combined with Chisels&Bits to make intricate detailed glass works.

I'm a little less enthusiastic about glowing variations.. but I can see their being a desire for such blocks, and I can see where they could be used to create some interesting creations. ( I'm mostly enthusiastic about using this with C&B to create bright colored patterns in dark stone. )

That said I believe it might be pretty limited by default....

The mod by default uses about 81 block ids if memory serves, adding just 1 shade of glass, and 1 shade of glow would take that too 243 (3x of what it is now)

I could mitigate that by make per type HSV/varation settings, but Its a legitimate concern with how I do the blocks since the main reason I did FCB was to enhance C&B's capabilities.

I'll think about it some, but I think its a good idea even if I need to add extra configurations.

As for crafting I think the same tool could be used but require an extra material ( such as glowstone for glow, or glass instead of cobble for glass )

**Comment by nnystyxx** [comment]
I believe one step of transparency (MC stained-glass level) and one step of glow (total self-illumination, xy-esque?) would already be a step in the right direction. I've been instantly obsessed with C&B since I saw it come out-- I love the mini-blocks concept, a gap that I hadn't had filled since Minepainter/DaVincing dropped off the map somewhat. And it's easily the best implementation OF that concept I've seen, with the usage of patterns, modes, and-- probably one of the absolute most impressive features in my eyes, the ability to ignore block grids. 

But enough gushing-- thank you very much for your swift response and satisfactory explanation. I agree on a lot of your ideas for implementation, and I look forward to seeing where C&B and FCB go from here.

EDIT: Armourer's Workshop itself, my example, only uses one 'step' of transparency and glow itself. Worth peeking at.

**Comment by AlgorithmX2** [comment]
Should be ready.. will probably release FCB 1.2 tomorrow.
