### ISSUE TITLE
Glowing white bits don't glow

### ISSUE THREAD

**Issue by jjc54** [ChiselsAndBits/FlatColoredBlocks#19]
Chisel and Bits: chiselsandbits-11.5
FCB: flatcoloredblocks-mc1.10-v4.1
Screens: http://imgur.com/a/pgyUT

Screen 1: a regular Glowing White Block emits light.
Screen 2: When turned into bits, they no longer emit light.
Screen 3: Oddly enough, other blocks such as Glowing Silver Block emit light even as bits.

**Comment by AlgorithmX2** [comment]
Two things, please take a screen shot of your F3 screen. and also try placing a full plane of glowing white bits.

**Comment by jjc54** [comment]
Alright. http://imgur.com/a/k8ajL
It seems that when I place down a full plane, no light is emitted. However, if I place down two planes right next to one another, they emit light. I tried just simply causing a block update and that didn't seem to work.

**Comment by AlgorithmX2** [comment]
The reason your glowing bits are not "glowing" in the dark is because you have optifine installed, it doesn't support the forge pipeline so I can't do glow-in-the-dark faces.

As for emitting light I would try placing down glowstone and then removing it, I think its a strange glitch where MC doesn't update the light levels accurately, but if you place and remove another light-source it seems to resolve it.

If that is the case its a known issue with C&B I've just not had time to track it down yet. I've created an issue for that on C&B Here ( https://github.com/AlgorithmX2/Chisels-and-Bits/issues/81 )

**Comment by jjc54** [comment]
Darn I was really hoping it wasn't Optifine. Thanks for the info though.

Yes you are correct. Placing another light source and removing it solves the strange light update glitch.

**Comment by AlgorithmX2** [comment]
Yep figured as much, gonna go ahead and close this issue.
