### ISSUE TITLE
Flat Colored Stairs 

### ISSUE THREAD

**Issue by Dijkstra1-zz** [ChiselsAndBits/FlatColoredBlocks#20]
Stairs made out of flat colored blocks would be nice, at the moment the only way is chisel and bits, least it has copy and past or don't think I would done that.

**Comment by AlgorithmX2** [comment]
I don't really see a downside to using C&B to do stairs, it takes 1 click to create the corner, 2 to create a straight and 3 to create a turn. Its incredibly easy to make basic stairs with C&B

And since FCB's goal is to not make things simple and compatible I won't be making stairs with tile entities, which means that the block id requirements for this would probably be far too high, well over double what are used for the blocks themselves.

**Comment by Dijkstra1-zz** [comment]
I know C&B can do stairs that fine, but it no first thought, when it comes to making stairs.  Also C & B does not have to be in every pack that Flat Colored blocks are in. 
By all means less tiles entities, I once regretted making my floors completely out of conduit facades, do flat colored blocks are tile entities, if so I might need to rethink making my base out of them.

**Comment by AlgorithmX2** [comment]
Flat colored blocks are NOT tile entities, and that's specifically the reason that its a problem.

Also not all Tile Entities are created equal, they very from mod to mod, and type to type. Some tick, some just store data, others calculate connections, or have super fancy rendering.

I realize that not every pack will have C&B, in fact there are probably other mods that can be used to make stairs, for instance on older versions of MC there are carpenter blocks, maybe even a mod on 1.10, that preforms a similar function.

But back the issue, by default FCB has 3870 shades, which currently uses around ~250 block ids, If I made a stair block for every single one of those shades, it would consume an additional 3870 block ids, exceeding minecrafts limit of 4096 with just the one mod.

So i'm left with 3 options,
1. Limit shades that can have stairs, but which to hide? this ends badly cause i'll probably ignore the shades you wanted to use.
2. Use a tile entity for stairs, this is doable, but it sort of goes against the principles of FCB as a whole.
3. Rely on another mod, such as C&B to provide stairs for the blocks FCB adds.

From where I'm sitting 3 seems to be the best solution. Its already there, and ready to use and I don't generally see a reason why pack authors would not want to use C&B, especially because of its extensive configuration options.

**Comment by Dijkstra1-zz** [comment]
C & B it is then and yes C & B is a good mod
