### ISSUE TITLE
Major Issue With Color Manager Still Present in Latest Release

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ChiselsAndBits/FlatColoredBlocks#27]
https://gist.github.com/P3rf3ctXZer0/30b7f68ef955147218107c3046819672

**Comment by AlgorithmX2** [comment]
Whats this "ColorHelper"? I have no idea what that is, is some other mod trying to analyize Flat Colored Blocks and RailCrafts Textures?

"Resource not usable as image: railcraft:textures/blocks/manipulator_dispenser_train_1.png"

"ColorHelper.setBlockColor(pass=frameTextureData): Couldn't derive RGBA from BlockMD [frsm:lamp:frsm:lamp[color=orange]]()
[01:41:30] [Client thread/WARN]: Texture was completely transparent for BlockMD [frsm:lamp:frsm:lamp[color=orange]]()"

I don't know what mod is trying to read these textures, however in the case of FCB,
"Resource not usable as image: flatcoloredblocks:textures/flatcoloredblock_SEMI_GLASS_127.png"

Is because that file dosn't exist, FCB generates it at runtime with the proper transparency and adds it to the texture atlas.

This is a problem with some other mod, I know not which.

**Comment by P3rf3ctXZer0** [comment]
Check with the following - Railcraft - Journeymap and Optifine. I am not a coder just a debugger... and I am sorry for that. If it helps I can give you the modlist I am using or even a direct link to my pack :)

**Comment by AlgorithmX2** [comment]
Seems to be JourneyMap, there are several logs and class that seems related. "ColorHelper_1_8" 

with various logging inside of it 

"this.logger.warn(String.format("Failed to use MaterialMapColor, marking block transparent: %s", new Object[] { blockMD }));" for instance.

I'd say that is the place to report this if its an issue for you.

**Comment by P3rf3ctXZer0** [comment]
Understood; thank you :)
