### ISSUE TITLE
Blocks that shimmer when inside an electric field

### ISSUE THREAD

**Issue by rahangar** [ChiselsAndBits/FlatColoredBlocks#28]
Not sure if electric fields have been a thing in modded minecraft for a while, but the Tesla coil introduced by Immersive Engineering seems to generate a field which causes Fluorescent Tubes placed within that field, to shimmer.   

This is a request to create a block (similar to the glowing FCB blocks) that will shimmer when placed within  an electric field.   

thanks,

**Comment by AlgorithmX2** [comment]
I'm not sure this makes sense for FCB, FCB tends to be a pretty basic 'vanilla' type mod, and this feature would require IE.

I'm not sure there is even a proper way to tie into them... but either way the first point stills stands, I'm not sure it belongs here.

**Comment by rahangar** [comment]
Oh ok.  I asked blu as well.  You can read his response here.  

https://github.com/BluSunrize/ImmersiveEngineering/issues/1733

Main reason why I asked it from FCB is because for my use case I intend to chisel the block, so for me the block has to be chiselable.  That way I can pepper the bits around my artwork and turn on/off groups of bits by switching on/off the telia coil.  

Btw what is it about a block that makes it chiselable?  I've tried chiseling blocks like the scaffolding from I.E. but no joy.   Does a block have to opt in somehow?

Thanks

**Comment by AlgorithmX2** [comment]
Blocks must basically be "normal full size with nothing special" Even if I did manage to add this feature to FCB, I would also have to add to C&B for it to work with it, and that is rather unlikely, because I'm trying to keep C&B away from potential performance issues.

As for options of swapping things around or animating, I hear you can use blood magics teleposer to move them around, maybe there are other blocks like that too that can help.

**Comment by rahangar** [comment]
I see.  Thanks anyway for considering it.  Also I've learned much from this dialogue.

Would it be possible to add the IE scaffolding blocks to C&B... if they are not too special that is.    I think at least one of them has connected textures.   Does that disqualify it as chiselable?

**Comment by AlgorithmX2** [comment]
It doesn't meet the basic criteria in some what, hard to say which one, or why.   Connected textures doesn't blatantly blacklist it, but they generally won't work.

If they are going to get white listed however @BluSunrize would likely be the one to ask, I don't white list peoples stuff on my side, if they want their things to work, they are free to do so however.

**Comment by BluSunrize** [comment]
I believe I already stated that it's basically impossible to make a block texture "light up" next to a Tesla Coil. The only reason the Fluorescent Tube can, is because it's an entity render and has access to OpenGL context. Blocks don't.
There is little help in just carrying the problem to another moddev after I have already explained the nigh-impossibility of making this happen.

**Comment by AlgorithmX2** [comment]
Sorry for the confusion Blu, I wasn't referring to that, I was referring to his request just above my last comment

"Would it be possible to add the IE scaffolding blocks to C&B... if they are not too special that is. I think at least one of them has connected textures. Does that disqualify it as chisel-able?"

**Comment by BluSunrize** [comment]
Algo, I'm aware of why I was initially summoned. But the base issue that started this thread is something that I had already answered. And I found it quite rude to bother another developer with something I had already declared a technical impossibility.
I don't want people to bother you because I declined a request ^^

**Comment by AlgorithmX2** [comment]
I guess, tho from the times it seems he asked both of us around the same time originally, I just hadn't replied until recently.

**Comment by rahangar** [comment]
Sorry Blu, I was unaware that you maintained all knowledge about all animation techniques, and that no one else could possibly have alternative ideas.

I also much appreciate the fact that you've taken the role of acting as a Mother to all modders and you're now mediating discussions between players, and identifying rude behavior.  Apologies for my rudeness.

From this point forward, I will make it a point to contact you first for all my minecraft questions.   And if you say "technically impossible", I'll stop asking others.   

Thanks again Blu

Algo, I'm already ashamed of my response above, but not enough to refrain.  Sorry I couldn't' resist, as I've seen this attitude from Blu on other threads.
