### ISSUE TITLE
crash when displaying FlatColoredBlocks creative tab

### ISSUE THREAD

**Issue by 0Navis0** [ChiselsAndBits/FlatColoredBlocks#50]
Everything is in the title. I use Minecraft 1.12.1 and Forge 14.22.0.2469. https://pastebin.com/vpFP4wy6

**Comment by AlgorithmX2** [comment]
This is likely a bug with mrcrayfish's mod, this happens when another mod renders all of its blocks in every creative tab.

The problem is that in 1.12 Vanilla added a new method that must be called in the existing method getSubItems, Example: https://github.com/AlgorithmX2/Chisels-and-Bits/commit/fb38943bce9c30c09773f2b3b03036b147266960#diff-617810317411c8f3ddf74d4e39088abb

**Comment by AlgorithmX2** [comment]
Mr Cray Fish has released a new version, please verify that your issue has been resolved.

**Comment by 0Navis0** [comment]
Yeah it works now, I close the issue. ;)
