### ISSUE TITLE
Crash when loading creative tab

### ISSUE THREAD

**Issue by Austin5003** [ChiselsAndBits/FlatColoredBlocks#54]
[crash-2017-11-13_22.16.43-client (fcb).txt](https://github.com/AlgorithmX2/FlatColoredBlocks/files/1472879/crash-2017-11-13_22.16.43-client.fcb.txt)
[crash-2017-11-13_22.40.55-client (fcb).txt](https://github.com/AlgorithmX2/FlatColoredBlocks/files/1472880/crash-2017-11-13_22.40.55-client.fcb.txt)

**Comment by AlgorithmX2** [comment]
omtteam.ompd.blocks.BlockFence Whatever mod this is part of is rendering their items in the FCB Creative tab. 

The problem is that in 1.12 Vanilla added a new method that must be called in the existing method getSubItems, Example: AlgorithmX2/Chisels-and-Bits@fb38943#diff-617810317411c8f3ddf74d4e39088abb

Please report this to the approriate mod dev.

**Comment by AlgorithmX2** [comment]
Looks like it already was reported to them, https://github.com/OpenModularTurretsTeam/OpenModularPassiveDefense/issues/13

**Comment by brisingraerowing** [comment]
The newest version fixes this.

**Comment by AlgorithmX2** [comment]
Thanks for the heads up.
