### ISSUE TITLE
Generate a list of RGB and HSV value?

### ISSUE THREAD

**Issue by pneumaticLance** [ChiselsAndBits/FlatColoredBlocks#59]
Is there (or is it possible to add) a command to generate a RGB and HSV value list of all the available flat color blocks in a text file? Kinda like how we can do an ID dump with NEI.

I'm trying to create a color palette from all the flat color blocks, so that I can do pixel art in drawing programs before translate it into Chisel&Bits in Minecraft. There is just too many blocks to manually record their values. It's kinda a reverse of issue #10 .

**Comment by AlgorithmX2** [comment]
This is what I was thinking after toying with it a bit, [flatcoloredblocks.xlsx](https://github.com/AlgorithmX2/FlatColoredBlocks/files/2771215/flatcoloredblocks.xlsx)

Am I missing anything? Note that the file it exports is a "CSV" and Github for some reason doesn't support those so I used GoogleDrive to convert it.

**Comment by pneumaticLance** [comment]
The format is perfect! I don't think we need blocks with light value in the list cause they don't have a real world application (unlike opacity that can be translated into alpha). I think opacity can probably be left out too since it's a duplicate of non-transparent value.

There is another thing I want to ask: is it possible to add 'show hex color in JEI tooltip'? This is to help searching specific color in JEI. Currently, searching by number return random results with the number in any field(name, RGB, HSV, opacity, light). Searching with hex color should solve the problem. (Another solution to help with searching is to change the '#' in the block names into another symbol that doesn't conflict with JEI, but that might make the names look weird)

**Comment by AlgorithmX2** [comment]
I see no reason to remove anything from the file, if you don't want to see it you could always edit the spreadsheet. Besides by default the transparent and glass blocks are similar, but you can configure them separately so that won't necessarily always be the case.

I've added HEX values to both the tool tips and the exported CSV, since those might be helpful.

Not really sure about changing the '#" in the name. Not sure what else I'd change it too. besides maybe "Num 32" or something which I'm not fond of. For lack of any real idea of what to do about that I went ahead and just added it to the localization file, so if you want to change it it would only be a resource pack away.

These changes will be in [6.7](https://minecraft.curseforge.com/projects/flat-colored-blocks/files/2661589)

**Comment by pneumaticLance** [comment]
Just tested 6.7 and it works perfectly! It even exported different block types in chunks for easy separation! Thank you so much for your hard work!
