### ISSUE TITLE
Can't get an even distribution of hues, saturations, or values

### ISSUE THREAD

**Issue by pressRtowin** [ChiselsAndBits/FlatColoredBlocks#64]
Have the exponent setting set to 1 for _everything_. I account for the fact that both the min and max are used and are using shade counts that should produce nice numbers. 26 (25+1) shades for saturation should produce 0, 4, 8, 12, 16, etc. but they don't. The numbers are all over the place. 145 shades for hue should produce 0, 2.5, 5, 7.5, 10, etc. but they don't. Am I doing something wrong?

**Comment by AlgorithmX2** [comment]
The internals of the mod are not designed for accuracy, because of some conversions and storage of how some values are stored and worked with trying to get perfectly accurate shades is not likely. The mod is designed to simply give a versatile array of colors, by the time I realized that this representation problem existed it was past the point of no return, already released and used by thousands of players.

**Comment by pressRtowin** [comment]
I believe my exact settings were 1 shade globally for all glowing and transparent blocks, every min set to 0, every max set to 1, every exponent set to 1, saturation and value shades for normal blocks set to 25, and hue shades for normal blocks set to 72. When hue shades was set to 71, it'd launch. When set to 72 it wouldn't.
